baseURL = "http://examplesite.org/"
disqusShortname = ""
googleAnalytics = ""
languageCode = "en-us"
languageName = "En"
paginate = "3"
summaryLength = "15"
theme = "bigspring"
title = "Local Ranker Pros"
[markup.goldmark.renderer]
unsafe = true
[[menu.footer_left]]
URL = "#"
name = "About Us"
[[menu.footer_left]]
URL = "#"
name = "Quick Start"
[[menu.footer_middle]]
URL = "#"
name = "Platform"
[[menu.footer_middle]]
URL = "#"
name = "Features"
[[menu.footer_right]]
URL = "privacy-policy"
name = "Privacy Policy"
[[menu.footer_right]]
URL = "faq"
name = "Contact Me"
[[menu.main]]
URL = "faq"
name = "Contact Me"
weight = 4
[[menu.main]]
URL = ""
name = "localrankerpros@gmail.com"
weight = ""
[params]
author = "Themefisher"
contact_form_action = "#"
copyright = "2021 Local Ranker Pros is a Trademark of Local Ranker Pros LLC"
description = "This is meta description"
footer_content = "Local Ranker Pros is the place for next-level local SEO service and local business growth strategies."
footer_menu_left = "Company"
footer_menu_middle = "Product"
footer_menu_right = "Support"
logo = "/images/local-ranker-pros-18.png"
logo_width = "200px"
[params.navigation_button]
enable = true
label = "Get Started"
link = "faq"
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[params.preloader]
enable = false
preloader = ""
[[params.social]]
icon = "ti-facebook"
link = "https://www.facebook.com/localrankerpros"
title = "facebook"
[[params.social]]
icon = "ti-twitter-alt"
link = "https://www.facebook.com/localrankerpros"
title = "twitter"
[[params.social]]
icon = "ti-skype"
link = "shaon.madyan"
title = "skype"
[[params.social]]
icon = "ti-linkedin"
link = "https://www.facebook.com/localrankerpros"
title = "linkedin"
